language: node_js

node_js:
  - 0.10

install:
  - npm install mocha-browser

script:
  - node_modules/.bin/mocha-browser tests/runner.html

after_success:
  - npm install jscoverage coveralls
  - node_modules/.bin/jscoverage --encoding=utf8 build build
  - node_modules/.bin/mocha-browser tests/runner.html -R lcov | node_modules/.bin/coveralls