language: node_js

node_js:
  - 0.10

install:
  - npm install mocha-phantomjs

script:
  - node_modules/.bin/mocha-phantomjs tests/runner.html

after_success:
  - npm install jscoverage mocha-lcov-reporter coveralls
  - node_modules/.bin/jscoverage --encoding=utf8 build build
  - node_modules/.bin/mocha-phantomjs tests/runner.html -R mocha-lcov-reporter | node_modules/.bin/coveralls